### ISSUE TITLE
Game crash on return to pullze room 2 after completion

### ISSUE THREAD

**Issue by PileUp120** [Bijeg/Mirrim#119]
1. current master
2. Game crash when returning to puzzle 2 after completing it
3. Windows 10 1903, RPG Maker MV 1.6.1
4. Walk to portal on the left after finishing puzzle 2 and moving to next room
5.Expected to return to room 2, actually crashes
6.Priority: critical

**Comment by wllmwng1** [comment]
Resolved with Pull request #120 .
