### ISSUE TITLE
Puzzle room state not restored when viewing memory fragment from menu

### ISSUE THREAD

**Issue by Dodeler** [Bijeg/Mirrim#48]
Commit hash: e1c6dfe3e32fdcc34ee32aa0f7f7b91f855e2590

Steps to reproduce:
1.  Enter first puzzle room
2.  Turn on laser
3.  Open menu and select first memory (opening cutscene)
4.  Observe laser is now 'off', player movement crashes

Expected: State is the same when returning from the cutscene
Actual: puzzle room is reset (but not the laser generator)

NOTE: This affects RPG maker setup (mirror directions for example) and the laser generator

Possible fix: event saver plugin

**Comment by wllmwng1** [comment]
This has been resolved with #63
