### ISSUE TITLE
Mirror Update doesn't work after memory fragments

### ISSUE THREAD

**Issue by wllmwng1** [Bijeg/Mirrim#87]
Commit: 0d129bb
Versions: Mac, Windows unknown, RPG Version 1.6.2
Issue: Mirror positions are not updating properly.
Steps: Move mirrors around. Go into a memory fragment. After memory is done, move mirrors again. Leave puzzle.
Expected: Mirrors are in position/direction as previous.
Actual: Mirrors are in position/direction as 2nd previous location.
Priority: Low
Edit: A quick fix might be to put on every single mirror <Save Event Location> instead of on just the map <Save Event Locations>, but that might be tedious.

**Comment by PileUp120** [comment]
Fixed in beta
