### ISSUE TITLE
Portal Events change colors

### ISSUE THREAD

**Issue by wllmwng1** [Bijeg/Mirrim#89]
Commit: 0d129bb
Versions: Mac, Windows unknown, RPG Version 1.6.2
Issue: Portal changes colour to red or green after some types of other events doing logic.
Steps:
Scenario 1 
1. Go through yellow memory portal in Puzzle 1.
Scenario 2 (In SolveStatic branch)
1. After going through memory fragment in Puzzle 2, portal going to next part of maze turns red.

Expected: Portal doesn't change colour.
Actual: Portal changes colour to red or green.

Possible Solve: I looked around and making Direction Fix to ON does solve some of them, but not all of them. Known example is Scenario 2.
Priority: Low

Note: This may cause user confusion mostly then break the game. If you can solve this problem there wouldn't be any user confusion about the portals.

**Comment by PileUp120** [comment]
Fixed in gold
